[package]
name = "bench"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mih-rs = { path = ".." }
rand = "0.8.4"

[[bin]]
name = "timeperf_topk"
path = "src/timeperf_topk.rs"
